<?php
/**
 * ACF Fields for Provider Post Type
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_provider_details',
        'title' => 'Provider Details',
        'fields' => array(
            // Basic Information
            array(
                'key' => 'field_url',
                'label' => 'URL',
                'name' => 'url',
                'type' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_parsed_at',
                'label' => 'Parsed At',
                'name' => 'parsed_at',
                'type' => 'date_time_picker',
                'required' => 0,
            ),
            array(
                'key' => 'field_status_code',
                'label' => 'Status Code',
                'name' => 'status_code',
                'type' => 'number',
                'required' => 0,
            ),
            array(
                'key' => 'field_content_length',
                'label' => 'Content Length',
                'name' => 'content_length',
                'type' => 'number',
                'required' => 0,
            ),
            array(
                'key' => 'field_geo',
                'label' => 'Geo',
                'name' => 'geo',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_title',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_status',
                'label' => 'Status',
                'name' => 'status',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_rating',
                'label' => 'Rating',
                'name' => 'rating',
                'type' => 'number',
                'min' => 0,
                'max' => 5,
                'step' => 0.1,
                'required' => 0,
            ),
            array(
                'key' => 'field_short_description',
                'label' => 'Short Description',
                'name' => 'short_description',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_insurance',
                'label' => 'Insurance',
                'name' => 'insurance',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_highlights',
                'label' => 'Highlights',
                'name' => 'highlights',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_main_image',
                'label' => 'Main Image',
                'name' => 'main_image',
                'type' => 'image',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_logo',
                'label' => 'Logo',
                'name' => 'logo',
                'type' => 'image',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_phone',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_website',
                'label' => 'Website',
                'name' => 'website',
                'type' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_image_gallery',
                'label' => 'Image Gallery',
                'name' => 'image_gallery',
                'type' => 'gallery',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_about',
                'label' => 'About',
                'name' => 'about',
                'type' => 'wysiwyg',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_video',
                'label' => 'Video',
                'name' => 'video',
                'type' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_insurance_accepted',
                'label' => 'Insurance Accepted',
                'name' => 'insurance_accepted',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_additional_info',
                'label' => 'Additional Info',
                'name' => 'additional_info',
                'type' => 'wysiwyg',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_technology_policy_description',
                'label' => 'Technology Policy Description',
                'name' => 'technology_policy_description',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_amenities_setting_description',
                'label' => 'Amenities Setting Description',
                'name' => 'amenities_setting_description',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_what_to_expect_description',
                'label' => 'What to Expect Description',
                'name' => 'what_to_expect_description',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_consistent_therapy_description',
                'label' => 'Consistent Therapy Description',
                'name' => 'consistent_therapy_description',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_verified_by_recovery',
                'label' => 'Verified by Recovery',
                'name' => 'verified_by_recovery',
                'type' => 'true_false',
                'ui' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_founded',
                'label' => 'Founded',
                'name' => 'founded',
                'type' => 'number',
                'required' => 0,
            ),
            array(
                'key' => 'field_estimated_cash_pay_rate',
                'label' => 'Estimated Cash Pay Rate',
                'name' => 'estimated_cash_pay_rate',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_occupancy',
                'label' => 'Occupancy',
                'name' => 'occupancy',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_who_we_treat',
                'label' => 'Who We Treat',
                'name' => 'who_we_treat',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_accreditation',
                'label' => 'Accreditation',
                'name' => 'accreditation',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_languages',
                'label' => 'Languages',
                'name' => 'languages',
                'type' => 'textarea',
                'rows' => 2,
                'required' => 0,
            ),
            array(
                'key' => 'field_address',
                'label' => 'Address',
                'name' => 'address',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_treatment_focus',
                'label' => 'Treatment Focus',
                'name' => 'treatment_focus',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_specializations',
                'label' => 'Specializations',
                'name' => 'specializations',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_treatment_services',
                'label' => 'Treatment Services',
                'name' => 'treatment_services',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_approaches',
                'label' => 'Approaches',
                'name' => 'approaches',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_therapies',
                'label' => 'Therapies',
                'name' => 'therapies',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_conditions_we_treat',
                'label' => 'Conditions We Treat',
                'name' => 'conditions_we_treat',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_substances_we_treat',
                'label' => 'Substances We Treat',
                'name' => 'substances_we_treat',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_aftercare',
                'label' => 'Aftercare',
                'name' => 'aftercare',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_personal_amenities',
                'label' => 'Personal Amenities',
                'name' => 'personal_amenities',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_amenities',
                'label' => 'Amenities',
                'name' => 'amenities',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_special_considerations',
                'label' => 'Special Considerations',
                'name' => 'special_considerations',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_activities',
                'label' => 'Activities',
                'name' => 'activities',
                'type' => 'textarea',
                'rows' => 3,
                'required' => 0,
            ),
            array(
                'key' => 'field_review',
                'label' => 'Review',
                'name' => 'review',
                'type' => 'textarea',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_page_title',
                'label' => 'Page Title',
                'name' => 'page_title',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_meta_description',
                'label' => 'Meta Description',
                'name' => 'meta_description',
                'type' => 'textarea',
                'rows' => 2,
                'required' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'provider',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
    ));
} 