<?php
/**
 * ACF Fields for Provider Post Type
 * New provider schema with reusable taxonomies
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_provider_details',
        'title' => 'Provider Details',
        'fields' => array(
            // ========================================
            // BASIC INFORMATION
            // ========================================
            array(
                'key' => 'field_provider_type',
                'label' => 'Provider Type',
                'name' => 'provider_type',
                'type' => 'taxonomy',
                'taxonomy' => 'provider-type',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'default_value' => 'treatment_facility',
                'required' => 0,
                'wrapper' => array(
                    'width' => '50',
                ),
            ),
            array(
                'key' => 'field_card_tier_badge',
                'label' => 'Card Tier',
                'name' => 'card_tier_badge',
                'type' => 'taxonomy',
                'taxonomy' => 'card-tier',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'default_value' => 'basic',
                'required' => 0,
                'wrapper' => array(
                    'width' => '50',
                ),
            ),
            array(
                'key' => 'field_subtitle',
                'label' => 'Subtitle',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => 'One sentence description for cards',
                'required' => 0,
            ),
            array(
                'key' => 'field_short_description_text',
                'label' => 'Short Description',
                'name' => 'short_description_text',
                'type' => 'textarea',
                'instructions' => 'Brief description with basic formatting (2-3 paragraphs)',
                'rows' => 4,
                'required' => 0,
            ),
            array(
                'key' => 'field_countries_list',
                'label' => 'Countries Served',
                'name' => 'countries_list',
                'type' => 'taxonomy',
                'taxonomy' => 'country',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_facility_type_list',
                'label' => 'Facility Types',
                'name' => 'facility_type_list',
                'type' => 'taxonomy',
                'taxonomy' => 'facility-type',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_service_delivery_method_list',
                'label' => 'Service Delivery Methods',
                'name' => 'service_delivery_method_list',
                'type' => 'taxonomy',
                'taxonomy' => 'service-delivery-method',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_independent_listing',
                'label' => 'Independent Listing',
                'name' => 'independent_listing',
                'type' => 'true_false',
                'instructions' => 'Show practitioner card independently AND within facility',
                'ui' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_enable_reviewer_functionality',
                'label' => 'Enable Reviewer Functionality',
                'name' => 'enable_reviewer_functionality',
                'type' => 'true_false',
                'instructions' => 'Enable this provider to be assigned as a medical reviewer for articles',
                'ui' => 1,
                'ui_on_text' => 'Enabled',
                'ui_off_text' => 'Disabled',
                'default_value' => 0,
                'required' => 0,
            ),

            // ========================================
            // CERTIFICATIONS & VERIFICATION
            // ========================================
            array(
                'key' => 'field_verifications_relation',
                'label' => 'Verifications',
                'name' => 'verifications_relation',
                'type' => 'relationship',
                'post_type' => array('verification'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),
            array(
                'key' => 'field_provider_credentials',
                'label' => 'Credentials',
                'name' => 'provider_credentials',
                'type' => 'text',
                'instructions' => 'Professional credentials (e.g., MD, PhD, Licensed, etc.)',
                'required' => 0,
                'default_value' => 'Healthcare Professional',
                'placeholder' => 'MD, PhD, Licensed',
            ),

            // ========================================
            // VISUAL CONTENT
            // ========================================
            array(
                'key' => 'field_image_url',
                'label' => 'Main Image',
                'name' => 'image_url',
                'type' => 'image',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_logo_url',
                'label' => 'Logo',
                'name' => 'logo_url',
                'type' => 'image',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_gallery_list',
                'label' => 'Image Gallery',
                'name' => 'gallery_list',
                'type' => 'gallery',
                'return_format' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_video_url',
                'label' => 'Promotional Video',
                'name' => 'video_url',
                'type' => 'url',
                'instructions' => 'URL to promotional video content',
                'required' => 0,
            ),

            // ========================================
            // PRICING & INSURANCE
            // ========================================
            array(
                'key' => 'field_insurance_accepted_list',
                'label' => 'Insurance Accepted',
                'name' => 'insurance_accepted_list',
                'type' => 'taxonomy',
                'taxonomy' => 'insurance',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_cost_range',
                'label' => 'Cost Range',
                'name' => 'cost_range',
                'type' => 'taxonomy',
                'taxonomy' => 'cost-range',
                'field_type' => 'select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'default_value' => '$',
                'required' => 0,
            ),
            array(
                'key' => 'field_pricing_details',
                'label' => 'Pricing Details',
                'name' => 'pricing_details',
                'type' => 'textarea',
                'instructions' => 'Comprehensive pricing and insurance policy information',
                'rows' => 4,
                'required' => 0,
            ),

            // ========================================
            // ADDITIONAL CONTENT & FILTERS
            // ========================================
            array(
                'key' => 'field_languages_list',
                'label' => 'Languages Offered',
                'name' => 'languages_list',
                'type' => 'taxonomy',
                'taxonomy' => 'language',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_services_list',
                'label' => 'Service Categories',
                'name' => 'services_list',
                'type' => 'taxonomy',
                'taxonomy' => 'service-category',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_conditions_list',
                'label' => 'Conditions Treated',
                'name' => 'conditions_list',
                'type' => 'taxonomy',
                'taxonomy' => 'condition',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_tags_list',
                'label' => 'Additional Tags',
                'name' => 'tags_list',
                'type' => 'taxonomy',
                'taxonomy' => 'provider-tag',
                'field_type' => 'checkbox',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'required' => 0,
            ),
            array(
                'key' => 'field_promo_article',
                'label' => 'Promotional Article',
                'name' => 'promo_article',
                'type' => 'wysiwyg',
                'instructions' => 'Rich promotional content with photos and formatting',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_program_overview',
                'label' => 'Program Overview',
                'name' => 'program_overview',
                'type' => 'wysiwyg',
                'instructions' => 'Rich program overview content with photos and formatting',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'required' => 0,
            ),
            array(
                'key' => 'field_mentioned_articles_relation',
                'label' => 'Mentioned Articles',
                'name' => 'mentioned_articles_relation',
                'type' => 'relationship',
                'post_type' => array('post'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),
            array(
                'key' => 'field_reviews_relation',
                'label' => 'Reviews',
                'name' => 'reviews_relation',
                'type' => 'relationship',
                'post_type' => array('review'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),

            // ========================================
            // TEAM & STAFF
            // ========================================
            array(
                'key' => 'field_practitioners_relation',
                'label' => 'Practitioners',
                'name' => 'practitioners_relation',
                'type' => 'relationship',
                'post_type' => array('provider'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),

            // ========================================
            // CATALOGUE & OFFERINGS
            // ========================================
            array(
                'key' => 'field_services_catalogue_relation',
                'label' => 'Services Catalogue',
                'name' => 'services_catalogue_relation',
                'type' => 'relationship',
                'post_type' => array('service'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),
            array(
                'key' => 'field_goods_catalogue_relation',
                'label' => 'Goods Catalogue',
                'name' => 'goods_catalogue_relation',
                'type' => 'relationship',
                'post_type' => array('product'),
                'multiple' => 1,
                'return_format' => 'id',
                'required' => 0,
            ),

            // ========================================
            // CONTACT & CTA
            // ========================================
            array(
                'key' => 'field_address',
                'label' => 'Primary Address',
                'name' => 'address',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_address_street',
                        'label' => 'Street Address',
                        'name' => 'street',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_city',
                        'label' => 'City',
                        'name' => 'city',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_state',
                        'label' => 'State/Province',
                        'name' => 'state',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_postal_code',
                        'label' => 'Postal Code',
                        'name' => 'postal_code',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_country',
                        'label' => 'Country',
                        'name' => 'country',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
                'required' => 0,
            ),
            array(
                'key' => 'field_phone',
                'label' => 'Primary Phone',
                'name' => 'phone',
                'type' => 'text',
                'required' => 0,
            ),
            array(
                'key' => 'field_email',
                'label' => 'Primary Email',
                'name' => 'email',
                'type' => 'email',
                'required' => 0,
            ),
            array(
                'key' => 'field_website_url',
                'label' => 'Website',
                'name' => 'website_url',
                'type' => 'url',
                'required' => 0,
            ),
            array(
                'key' => 'field_addresses_list',
                'label' => 'Additional Addresses',
                'name' => 'addresses_list',
                'type' => 'repeater',
                'layout' => 'block',
                'button_label' => 'Add Address',
                'sub_fields' => array(
                    array(
                        'key' => 'field_address_list_street',
                        'label' => 'Street Address',
                        'name' => 'street',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_list_city',
                        'label' => 'City',
                        'name' => 'city',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_list_state',
                        'label' => 'State/Province',
                        'name' => 'state',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_list_postal_code',
                        'label' => 'Postal Code',
                        'name' => 'postal_code',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_address_list_country',
                        'label' => 'Country',
                        'name' => 'country',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
                'required' => 0,
            ),
            array(
                'key' => 'field_phones_list',
                'label' => 'Additional Phone Numbers',
                'name' => 'phones_list',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Phone',
                'sub_fields' => array(
                    array(
                        'key' => 'field_phone_list_number',
                        'label' => 'Phone Number',
                        'name' => 'number',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_phone_list_label',
                        'label' => 'Label',
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => 'e.g., "Main Office", "Emergency", "Booking"',
                        'required' => 0,
                    ),
                ),
                'required' => 0,
            ),
            array(
                'key' => 'field_emails_list',
                'label' => 'Additional Email Contacts',
                'name' => 'emails_list',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Email',
                'sub_fields' => array(
                    array(
                        'key' => 'field_email_list_address',
                        'label' => 'Email Address',
                        'name' => 'email',
                        'type' => 'email',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_email_list_label',
                        'label' => 'Label',
                        'name' => 'label',
                        'type' => 'text',
                        'instructions' => 'e.g., "General Inquiries", "Bookings", "Support"',
                        'required' => 0,
                    ),
                ),
                'required' => 0,
            ),


        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'provider',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
    ));
} 